hyprland working config

diff --git a/modules/home-manager/scripts/set_wallpaper b/modules/home-manager/scripts/set_wallpaper
--- a/modules/home-manager/scripts/set_wallpaper
+++ b/modules/home-manager/scripts/set_wallpaper
@@ -29,20 +29,18 @@
 # echo "$2" # auto
 # echo "$3" # /home/username/Pictures/Wallpapers/Nature/green-tunnel-1920x1080-wallpaper-861.jpg
 
-
 # Here you may apply some additional custom operations on the wallpaper before it is applied.
 # In the end put the path to the actual final wallpaper image file in the WP variable.
 # The default is to simply set WP=$1.
 WP=$1
 
-
 # Enlightenment
 # Needs Modules/System/DBus Extension loaded to work
 if [[ "$DESKTOP" == *"Enlightenment"* ]] || [[ "$DESKTOP" == *"Moksha"* ]]; then
 
-    OUTPUT_DIR="$HOME/.e/e/backgrounds"
+	OUTPUT_DIR="$HOME/.e/e/backgrounds"
 
-    TEMPLATE='
+	TEMPLATE='
     images { image: "@IMAGE@" USER; }
     collections {
       group {
@@ -65,60 +63,60 @@ if [[ "$DESKTOP" == *"Enlightenment"* ]] || [[ "$DESKTOP" == *"Moksha"* ]]; then
     }
     '
 
-    OFILE="$OUTPUT_DIR/variety_wallpaper_$RANDOM"
+	OFILE="$OUTPUT_DIR/variety_wallpaper_$RANDOM"
 
-    DIMENSION="$(identify -format "%w/%h" "$WP")"
+	DIMENSION="$(identify -format "%w/%h" "$WP")"
 
-    if [ ! -z "$DIMENSION" ]; then
-        WIDTH="$(echo "$DIMENSION" | cut -d/ -f1)"
-        HEIGHT="$(echo "$DIMENSION" | cut -d/ -f2)"
-        IMAGE="$(echo "$WP" | sed 's/[^[:alnum:]_-]/\\&/g')"
+	if [ ! -z "$DIMENSION" ]; then
+		WIDTH="$(echo "$DIMENSION" | cut -d/ -f1)"
+		HEIGHT="$(echo "$DIMENSION" | cut -d/ -f2)"
+		IMAGE="$(echo "$WP" | sed 's/[^[:alnum:]_-]/\\&/g')"
 
-        if [ -z "$HEIGHT" ] || [ "$HEIGHT" = "0" ]; then
-            ASPECT="0.0"
-        else
-            ASPECT="$(echo "scale=9; $DIMENSION" | bc)"
-        fi
-    fi
+		if [ -z "$HEIGHT" ] || [ "$HEIGHT" = "0" ]; then
+			ASPECT="0.0"
+		else
+			ASPECT="$(echo "scale=9; $DIMENSION" | bc)"
+		fi
+	fi
 
-    printf "%s" "$TEMPLATE" | \
-    sed "s/@ASPECT@/$ASPECT/g; s/@WIDTH@/$WIDTH/g; s/@HEIGHT@/$HEIGHT/g; s|@IMAGE@|$IMAGE|g" > "$OFILE.edc"
-    edje_cc "$OFILE.edc" "$OFILE.edj" 2>/dev/null
-    rm "$OFILE.edc"
+	printf "%s" "$TEMPLATE" |
+		sed "s/@ASPECT@/$ASPECT/g; s/@WIDTH@/$WIDTH/g; s/@HEIGHT@/$HEIGHT/g; s|@IMAGE@|$IMAGE|g" >"$OFILE.edc"
+	edje_cc "$OFILE.edc" "$OFILE.edj" 2>/dev/null
+	rm "$OFILE.edc"
 
-    ## Get the current number of virtual desktops
-    desk_x_count=$(enlightenment_remote -desktops-get | awk '{print $1}')
-    desk_y_count=$(enlightenment_remote -desktops-get | awk '{print $2}')
+	## Get the current number of virtual desktops
+	desk_x_count=$(enlightenment_remote -desktops-get | awk '{print $1}')
+	desk_y_count=$(enlightenment_remote -desktops-get | awk '{print $2}')
 
-    ## Get the current number of screens
-    screen_count=1
-    # If xrandr is available use it to get screen desk_x_count
-    if command -v xrandr >/dev/null 2>&1; then
-        screen_count=$(xrandr -q | grep -c ' connected')
-    fi
+	## Get the current number of screens
+	screen_count=1
+	# If xrandr is available use it to get screen desk_x_count
+	if command -v xrandr >/dev/null 2>&1; then
+		screen_count=$(xrandr -q | grep -c ' connected')
+	fi
 
-    ## Set the wallpaper for each virtual desktop
-    for ((x=0; x<desk_x_count; x++)); do
-        for ((y=0; y<desk_y_count; y++)); do
-            for ((z=0; z<screen_count; z++)); do
-                # -desktop-bg-add OPT1 OPT2 OPT3 OPT4 OPT5 Add a desktop bg definition.
-                # OPT1 = ContainerNo OPT2 = ZoneNo OPT3 = Desk_x. OPT4 = Desk_y. OPT5 = bg file path
-                enlightenment_remote -desktop-bg-add 0 "$z" "$x" "$y" "$OFILE.edj"&
-            done
-        done
-    done
+	## Set the wallpaper for each virtual desktop
+	for ((x = 0; x < desk_x_count; x++)); do
+		for ((y = 0; y < desk_y_count; y++)); do
+			for ((z = 0; z < screen_count; z++)); do
+				# -desktop-bg-add OPT1 OPT2 OPT3 OPT4 OPT5 Add a desktop bg definition.
+				# OPT1 = ContainerNo OPT2 = ZoneNo OPT3 = Desk_x. OPT4 = Desk_y. OPT5 = bg file path
+				enlightenment_remote -desktop-bg-add 0 "$z" "$x" "$y" "$OFILE.edj" &
+			done
+		done
+	done
 
-    # Remove all Variety wallpapers, but the current one and the previous one
-    #   as we are calling enlightenment_remote asynchronously, if the previous wallpaper hasn't been
-    #   replaced yet then the wallpaper will get set back to the theme one causing ugly artifacts
-    LAST_WALLPAPER_FILE="/home/nik/.config/variety/.enlightenment_last_wallpaper.txt"
+	# Remove all Variety wallpapers, but the current one and the previous one
+	#   as we are calling enlightenment_remote asynchronously, if the previous wallpaper hasn't been
+	#   replaced yet then the wallpaper will get set back to the theme one causing ugly artifacts
+	LAST_WALLPAPER_FILE="/home/nik/.config/variety/.enlightenment_last_wallpaper.txt"
 
-    if [ -e "$LAST_WALLPAPER_FILE" ]; then
-        find "$OUTPUT_DIR" -name "variety_wallpaper*.*" | grep -v "$OFILE.edj" | grep -v "$(cat "$LAST_WALLPAPER_FILE")" | xargs rm
-    else
-        find "$OUTPUT_DIR" -name "variety_wallpaper*.*" | grep -v "$OFILE.edj" | xargs rm
-    fi
-    echo "$OFILE.edj" > "$LAST_WALLPAPER_FILE"
+	if [ -e "$LAST_WALLPAPER_FILE" ]; then
+		find "$OUTPUT_DIR" -name "variety_wallpaper*.*" | grep -v "$OFILE.edj" | grep -v "$(cat "$LAST_WALLPAPER_FILE")" | xargs rm
+	else
+		find "$OUTPUT_DIR" -name "variety_wallpaper*.*" | grep -v "$OFILE.edj" | xargs rm
+	fi
+	echo "$OFILE.edj" >"$LAST_WALLPAPER_FILE"
 fi
 
 # KDE: Users on KDE 4 or Plasma < 5.7 will have to manually choose ~/Pictures/variety-wallpaper/ as a slideshow folder with a short interval.
@@ -126,19 +124,19 @@ fi
 # and KDE will refresh it
 # On Plasma 5.7 and above, the wallpaper choosing is automatic.
 if [ "${KDE_FULL_SESSION}" == "true" ]; then
-    # Plasma 5.7 introduced a new feature to set the wallpaper via a qdbus script:
-    # https://github.com/KDE/plasma-workspace/commit/903cbfd7e267a4812a6ec222eb7e1b5dd775686f
-    if [[ -n "${KDE_SESSION_VERSION}" && "${KDE_SESSION_VERSION}" == '5' ]]; then
+	# Plasma 5.7 introduced a new feature to set the wallpaper via a qdbus script:
+	# https://github.com/KDE/plasma-workspace/commit/903cbfd7e267a4812a6ec222eb7e1b5dd775686f
+	if [[ -n "${KDE_SESSION_VERSION}" && "${KDE_SESSION_VERSION}" == '5' ]]; then
 
-        # Try to find the Qt 5 version of qdbus. For systems using qtchooser, the binary name is 'qdbus'
-        # and the Qt version can be selected via the QT_SELECT environment variable.
-        if command -v qdbus-qt5 &>/dev/null; then
-            qdbus_command=qdbus-qt5
-        else
-            qdbus_command=qdbus
-        fi
+		# Try to find the Qt 5 version of qdbus. For systems using qtchooser, the binary name is 'qdbus'
+		# and the Qt version can be selected via the QT_SELECT environment variable.
+		if command -v qdbus-qt5 &>/dev/null; then
+			qdbus_command=qdbus-qt5
+		else
+			qdbus_command=qdbus
+		fi
 
-        QT_SELECT=5 $qdbus_command org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "
+		QT_SELECT=5 $qdbus_command org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "
         var allDesktops = desktops();
         for (i=0; i < allDesktops.length; i++) {
             d = allDesktops[i];
@@ -147,79 +145,79 @@ if [ "${KDE_FULL_SESSION}" == "true" ]; then
             d.writeConfig('Image', 'file://""$WP""')
         }
         "
-        # Reuse the exit code from qdbus
-        qdbus_exitcode="$?"
+		# Reuse the exit code from qdbus
+		qdbus_exitcode="$?"
 
-        if [[ "$qdbus_exitcode" -ne 0 ]]; then
-            # If the script fails, show a notification.
-            kdialog --title "Variety: cannot change Plasma wallpaper" --passivepopup "Could not change the Plasma 5 wallpaper; \
+		if [[ "$qdbus_exitcode" -ne 0 ]]; then
+			# If the script fails, show a notification.
+			kdialog --title "Variety: cannot change Plasma wallpaper" --passivepopup "Could not change the Plasma 5 wallpaper; \
                 make sure that you're using Plasma 5.7+ and have widgets unlocked.\n----\n \
                 Due to Plasma limitations, external programs cannot automatically change the wallpaper when the widgets are locked.\n \
-                See https://git.io/vprpM for more information." --icon variety 10  # Final number is the length of the popup
-        fi
-        exit "$qdbus_exitcode"
+                See https://git.io/vprpM for more information." --icon variety 10 # Final number is the length of the popup
+		fi
+		exit "$qdbus_exitcode"
 
-    else
-        WALLDIR="$(xdg-user-dir PICTURES)/variety-wallpaper"
-        mkdir -p "$WALLDIR"
-        # Remove all old wallpapers
-        rm -fv "${WALLDIR}"/*
+	else
+		WALLDIR="$(xdg-user-dir PICTURES)/variety-wallpaper"
+		mkdir -p "$WALLDIR"
+		# Remove all old wallpapers
+		rm -fv "${WALLDIR}"/*
 
-        NEWWP="${WALLDIR}/wallpaper-kde-$RANDOM.jpg"
-        cp "$WP" "$NEWWP"
-        touch "$NEWWP"
-    fi
+		NEWWP="${WALLDIR}/wallpaper-kde-$RANDOM.jpg"
+		cp "$WP" "$NEWWP"
+		touch "$NEWWP"
+	fi
 fi
 
 # Gnome 3, Unity
-gsettings set org.gnome.desktop.background picture-uri "file://$WP" 2> /dev/null
-gsettings set org.gnome.desktop.background picture-uri-dark "file://$WP" 2> /dev/null
+gsettings set org.gnome.desktop.background picture-uri "file://$WP" 2>/dev/null
+gsettings set org.gnome.desktop.background picture-uri-dark "file://$WP" 2>/dev/null
 if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
-    gsettings set org.gnome.desktop.background picture-options "$4"
+	gsettings set org.gnome.desktop.background picture-options "$4"
 fi
-if [ "$(gsettings get org.gnome.desktop.background picture-options)" == "'none'"  ]; then
-    gsettings set org.gnome.desktop.background picture-options 'zoom'
+if [ "$(gsettings get org.gnome.desktop.background picture-options)" == "'none'" ]; then
+	gsettings set org.gnome.desktop.background picture-options 'zoom'
 fi
 
 # GNOME Screensaver / Lock screen - thanks to George C. de Araujo for the patch
-gsettings set org.gnome.desktop.screensaver picture-uri "file://$WP" 2> /dev/null
+gsettings set org.gnome.desktop.screensaver picture-uri "file://$WP" 2>/dev/null
 if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
-    gsettings set org.gnome.desktop.screensaver picture-options "$4"
+	gsettings set org.gnome.desktop.screensaver picture-options "$4"
 fi
 if [ "$(gsettings get org.gnome.desktop.screensaver picture-options)" == "'none'" ]; then
-    gsettings set org.gnome.desktop.screensaver picture-options 'zoom'
+	gsettings set org.gnome.desktop.screensaver picture-options 'zoom'
 fi
 
 # Deepin
 if [ "$(gsettings list-schemas | grep -c com.deepin.wrap.gnome.desktop.background)" -ge 1 ]; then
-    gsettings set com.deepin.wrap.gnome.desktop.background picture-uri "file://$WP"
-    if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
-        gsettings set com.deepin.wrap.gnome.desktop.background picture-options "$4"
-    fi
-    if [ "$(gsettings get com.deepin.wrap.gnome.desktop.background picture-options)" == "'none'" ]; then
-        gsettings set com.deepin.wrap.gnome.desktop.background picture-options 'zoom'
-    fi
+	gsettings set com.deepin.wrap.gnome.desktop.background picture-uri "file://$WP"
+	if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
+		gsettings set com.deepin.wrap.gnome.desktop.background picture-options "$4"
+	fi
+	if [ "$(gsettings get com.deepin.wrap.gnome.desktop.background picture-options)" == "'none'" ]; then
+		gsettings set com.deepin.wrap.gnome.desktop.background picture-options 'zoom'
+	fi
 fi
 
 # XFCE
 command -v xfconf-query >/dev/null 2>&1
 rc=$?
-if [[ $rc = 0 ]] ; then
-    for i in $(xfconf-query -c xfce4-desktop -p /backdrop -l | grep -E -e "screen.*/monitor.*image-path$" -e "screen.*/monitor.*/last-image$"); do
-        xfconf-query -c xfce4-desktop -p "$i" -n -t string -s "" 2> /dev/null
-        xfconf-query -c xfce4-desktop -p "$i" -s "" 2> /dev/null
-        xfconf-query -c xfce4-desktop -p "$i" -s "$WP" 2> /dev/null
-    done
+if [[ $rc = 0 ]]; then
+	for i in $(xfconf-query -c xfce4-desktop -p /backdrop -l | grep -E -e "screen.*/monitor.*image-path$" -e "screen.*/monitor.*/last-image$"); do
+		xfconf-query -c xfce4-desktop -p "$i" -n -t string -s "" 2>/dev/null
+		xfconf-query -c xfce4-desktop -p "$i" -s "" 2>/dev/null
+		xfconf-query -c xfce4-desktop -p "$i" -s "$WP" 2>/dev/null
+	done
 fi
 
 # LXDE/PCmanFM
 if [ "$XDG_CURRENT_DESKTOP" == "LXDE" ]; then
-    pcmanfm --set-wallpaper "$WP" 2> /dev/null
+	pcmanfm --set-wallpaper "$WP" 2>/dev/null
 fi
 
 # LXQt/PCmanFM-qt
 if [ "$XDG_CURRENT_DESKTOP" == "LXQt" ]; then
-    pcmanfm-qt --set-wallpaper "$WP" 2> /dev/null
+	pcmanfm-qt --set-wallpaper "$WP" 2>/dev/null
 fi
 
 # For simple WMs, use either feh or nitrogen
@@ -227,55 +225,70 @@ fi
 # This also means that an empty variable won't cause false positives, since it expands to "  "
 SIMPLE_WMS=("bspwm" "dwm" "herbstluftwm" "i3" "i3-with-shmlog" "jwm" "LeftWM" "openbox" "qtile" "qtile-venv" "xmonad" "none+bspwm" "none+dwm" "none+herbstluftwm" "none+i3" "none+i3-with-shmlog" "none+jwm" "none+LeftWM" "none+openbox" "none+qtile" "none+qtile-venv" "none+xmonad")
 if [[ " ${SIMPLE_WMS[*]} " = *" $XDG_CURRENT_DESKTOP "* || " ${SIMPLE_WMS[*]} " = *" $XDG_SESSION_DESKTOP "* ||
-      " ${SIMPLE_WMS[*]} " = *" $DESKTOP_SESSION "* ]]; then
+	" ${SIMPLE_WMS[*]} " = *" $DESKTOP_SESSION "* ]]; then
 	if command -v "feh" >/dev/null 2>&1; then
-	      # TODO: This should take the scaling parameter $4 into account and use other options than --bg-fill
-        feh --bg-fill "$WP" 2> /dev/null
-    elif command -v "nitrogen" >/dev/null 2>&1; then
-	      # TODO: This should take the scaling parameter $4 into account and use other options than --set-zoom-fill
-        nitrogen --set-zoom-fill --save "$WP" 2> /dev/null
-    fi
+		# TODO: This should take the scaling parameter $4 into account and use other options than --bg-fill
+		feh --bg-fill "$WP" 2>/dev/null
+	elif command -v "nitrogen" >/dev/null 2>&1; then
+		# TODO: This should take the scaling parameter $4 into account and use other options than --set-zoom-fill
+		nitrogen --set-zoom-fill --save "$WP" 2>/dev/null
+	fi
+fi
+
+if [[ -n $HYPRLAND_INSTANCE_SIGNATURE ]]; then
+	# If swaybg is available, use it as prevents system freeze.
+	# See https://github.com/swaywm/sway/issues/5606
+	if command -v "swaybg" >/dev/null 2>&1; then
+		# Grey background flicker is prevented by killing old swaybg process after new one.
+		# See https://github.com/swaywm/swaybg/issues/17#issuecomment-851680720
+		PID=$(pidof swaybg)
+		swaybg -i "$WP" -m fill &
+		if [ ! -z "$PID" ]; then
+			sleep 1
+			kill $PID 2>/dev/null
+		fi
+	fi
 fi
 
 if [[ -n $SWAYSOCK ]]; then
-    # If swaybg is available, use it as prevents system freeze.
-    # See https://github.com/swaywm/sway/issues/5606
-    if command -v "swaybg" >/dev/null 2>&1; then
-        # Grey background flicker is prevented by killing old swaybg process after new one.
-        # See https://github.com/swaywm/swaybg/issues/17#issuecomment-851680720
-        PID=`pidof swaybg`
-        swaybg -i "$WP" -m fill &
-        if [ ! -z "$PID" ]; then
-            sleep 1
-            kill $PID 2>/dev/null
-        fi
-    else
-        swaymsg output "*" bg "$WP" fill 2> /dev/null
-    fi
+	# If swaybg is available, use it as prevents system freeze.
+	# See https://github.com/swaywm/sway/issues/5606
+	if command -v "swaybg" >/dev/null 2>&1; then
+		# Grey background flicker is prevented by killing old swaybg process after new one.
+		# See https://github.com/swaywm/swaybg/issues/17#issuecomment-851680720
+		PID=$(pidof swaybg)
+		swaybg -i "$WP" -m fill &
+		if [ ! -z "$PID" ]; then
+			sleep 1
+			kill $PID 2>/dev/null
+		fi
+	else
+		swaymsg output "*" bg "$WP" fill 2>/dev/null
+	fi
 fi
 
 # trinity
 if [ "$XDG_CURRENT_DESKTOP" == "Trinity" ]; then
-    # The 4 refers to display mode 4; valid ones are 1-8
-    dcop kdesktop KBackgroundIface setWallpaper "$WP" 4 2> /dev/null
+	# The 4 refers to display mode 4; valid ones are 1-8
+	dcop kdesktop KBackgroundIface setWallpaper "$WP" 4 2>/dev/null
 fi
 
 # MATE after 1.6
-gsettings set org.mate.background picture-filename "$WP" 2> /dev/null
+gsettings set org.mate.background picture-filename "$WP" 2>/dev/null
 if [ "$(gsettings get org.mate.desktop.background picture-options 2>/dev/null)" == "'none'" ]; then
 	gsettings set org.mate.desktop.background picture-options 'zoom'
 fi
 if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
-  gsettings set org.mate.desktop.background picture-options "$4"
+	gsettings set org.mate.desktop.background picture-options "$4"
 fi
 
 # Cinnamon after 2.0
-gsettings set org.cinnamon.desktop.background picture-uri "file://$WP" 2> /dev/null
+gsettings set org.cinnamon.desktop.background picture-uri "file://$WP" 2>/dev/null
 if [ "$(gsettings get org.cinnamon.desktop.background picture-options 2>/dev/null)" == "'none'" ]; then
 	gsettings set org.cinnamon.desktop.background picture-options 'zoom'
 fi
 if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
-  gsettings set org.cinnamon.desktop.background picture-options "$4"
+	gsettings set org.cinnamon.desktop.background picture-options "$4"
 fi
 
 # Awesome Window Manager
